inherit_from: .rubocop_todo.yml

require:
  - rubocop-capybara
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  Exclude:
    - bin/bundle
    - config/environments/*.rb
    - features/support/env.rb
    - lib/tasks/cucumber.rake
    - db/schema.rb
    - db/migrate/*.rb

Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Max: 200

Metrics/BlockLength:
  Exclude:
    - config/routes.rb

Style/GlobalStdStream:
  Exclude:
    - config/environments/production.rb

Style/RedundantFetchBlock:
  Exclude:
    - config/puma.rb

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Max: 15

Rails/I18nLocaleTexts:
  Enabled: false

Style/ClassAndModuleChildren:
  Exclude:
    - app/models/**/*.rb