name: RSpec
on:
  workflow_dispatch: {}
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: anki_books
          POSTGRES_DB: anki_books_test
          POSTGRES_PASSWORD: postgres
        ports:
        - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
      - run: bundle install
      - name: Setup test database
        env:
          RAILS_ENV: test
          PGHOST: localhost
          POSTGRES_DB: anki_books_test
          POSTGRES_USER: anki_books
          POSTGRES_PASSWORD: postgres
        run: |
          cp config/database.ci.yml config/database.yml
          bin/rails db:setup
      - name: Run specs
        env:
          PGHOST: localhost
          POSTGRES_DB: anki_books_test
          POSTGRES_USER: anki_books
          POSTGRES_PASSWORD: postgres
          PGPORT: 5432
          RAILS_ENV: test
        run: bundle exec rspec
      - name: Upload SimpleCov artifact
        uses: actions/upload-artifact@v4
        with:
          name: RSpec tests coverage
          path: coverage/
