name: RSpec
on:
  workflow_dispatch: {}
jobs:
  run_specs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
      - run: bundle install
      - run: bundle exec rspec
      - name: Upload SimpleCov artifact
        uses: actions/upload-artifact@v4
        with:
          name: RSpec tests coverage
          path: coverage/
